ARG from
FROM $from

ARG target_tag

COPY etc/ /etc/
COPY usr/ /usr/

COPY fwload/usr/ /usr/
COPY usbnet/etc/ /etc/
COPY usbnet/usr/ /usr/

# qualcomm tools and libs
RUN dnf -y install \
    hexagonrpc \
    bootmac \
    tqftpserv \
    qbootctl \
    rmtfs \
    qcom-firmware \
    pil-squasher \
    pd-mapper \
    libssc \
    qrtr

RUN systemctl enable \
    hexagonrpcd-sdsp.service \
    bootmac-bluetooth.service \
    tqftpserv.service \
    qbootctl.service \
    rmtfs.service

# audio
RUN dnf -y install \
    alsa-utils \
    pipewire \
    pipewire-alsa \
    pipewire-pulseaudio \
    alsa-ucm-mobility-sdm845 \
    q6voiced

RUN systemctl enable \
    q6voiced.service
RUN systemctl mask \
    alsa-state.service \
    alsa-restore.service

# other
RUN dnf -y install \
    ath10k-shutdown \
    mobility-tweaks \
    buffyboard \
    dnsmasq

RUN systemctl enable \
    msm-modem-uim-selection.service

# kernel
RUN mkdir /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    rm -rf /usr/lib/modules/* && \
    dnf -y install kernel && \
    rm -rf /boot/dtb

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
