ARG from
FROM $from

ARG target_tag

COPY etc/ /etc/

RUN dnf -y install \
    nothing-spacewar-firmware \
    alsa-ucm-conf-qcom-sc7280 \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    dnf -y install kernel && \
    rm -r /boot/dtb

# services
RUN systemctl enable \
    tqftpserv.service \
    qbootctl.service \
    rmtfs.service

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
