ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    dnf -y install kernel-0:6.16.0-0.sm8150.fc42 && \
    rm -r /boot/dtb

RUN dnf -y install \
    xiaomi-nabu-firmware \
    xiaomi-nabu-audio \
    qbootctl

RUN systemctl enable qbootctl.service

# clenup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
