ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra \
        kernel-devel \
        kernel-headers && \
    dnf -y install kernel && \
    dnf -y install \
        alsa-ucm-conf-xiaomi-nabu \
        xiaomi-nabu-firmware \
        qbootctl \
        btop && \
    systemctl enable qbootctl.service && \
    dnf clean all && \
    bootc container lint
