ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

RUN mkdir -p /boot/dtb && \
    dnf -y copr enable gmanka/sm8150 && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra \
        kernel-devel \
        kernel-headers && \
    dnf -y install kernel-*.sm8150.* && \
    dnf -y copr enable nik012003/nabu-support && \
    dnf -y install \
        alsa-ucm-conf-xiaomi-nabu \
        xiaomi-nabu-firmware \
        tqftpserv \
        pd-mapper \
        qbootctl \
        rmtfs \
        qrtr && \
    systemctl enable rmtfs.service && \
    systemctl enable tqftpserv.service && \
    systemctl enable qbootctl.service && \
    dnf clean all && \
    bootc container lint
