#!/usr/bin/env bash

set -uexo pipefail

# Files

cp -arfT files/etc /etc
cp -arfT files/usr /usr

cp -arfT files/usbnet/etc /etc
cp -arfT files/usbnet/usr /usr

cp -arfT files/fwload/etc /etc
cp -arfT files/fwload/usr /usr

# Qualcomm tools and libs

dnf -y install \
    hexagonrpc \
    bootmac \
    tqftpserv \
    qbootctl \
    rmtfs \
    qcom-firmware \
    droid-juicer \
    pd-mapper \
    libssc \
    qrtr

systemctl enable \
    hexagonrpcd-sdsp.service \
    bootmac-bluetooth.service \
    tqftpserv.service \
    qbootctl.service \
    rmtfs.service

# services for firmware extraction
systemctl enable \
    droid-juicer.service \
    ostree-state-overlay@usr-lib-firmware-updates.service \
    restart-remoteproc.service

# Audio

dnf -y install \
    alsa-utils \
    pipewire \
    pipewire-alsa \
    pipewire-pulseaudio \
    alsa-ucm-mobility-sdm845 \
    q6voiced

systemctl enable \
    q6voiced.service

systemctl mask \
    alsa-state.service \
    alsa-restore.service

# Other

dnf -y install \
    ath10k-shutdown \
    mobility-tweaks \
    buffyboard \
    dnsmasq

systemctl enable \
    msm-modem-uim-selection.service

# Kernel

mkdir /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
rm -rf /usr/lib/modules/*
dnf -y install kernel kernel-modules-extra
rm -rf /boot/dtb
