ARG base_name
ARG base_tag

FROM quay.io/pocketblue/$base_name:$base_tag

RUN dnf -y install 'dnf5-command(copr)' && \
    dnf -y copr enable samcday/phrog && \
    dnf -y install @phosh-desktop phrog && \
    systemctl enable --force phrog.service && \
    dnf clean all
