ARG from
FROM $from

RUN dnf -y install 'dnf5-command(copr)' && \
    dnf -y copr enable samcday/phrog && \
    dnf -y install \
        @phosh-desktop \
        phrog \
        gnome-software-rpm-ostree \
        default-flatpaks && \
    systemctl enable --force phrog.service && \
    dnf clean all
