ARG from
FROM $from

COPY etc/ /etc/

RUN dnf -y install \
    @phosh-desktop \
    phrog \
    gnome-software-rpm-ostree \
    nautilus \
    ptyxis \
    default-flatpaks \
    --exclude gnome-calculator
    --exclude gnome-calendar
    --exclude gnome-clocks
    --exclude gnome-console
    --exclude gnome-contacts
    --exclude gnome-maps
    --exclude gnome-photos

RUN systemctl enable --force phrog.service

# clenup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
