#!/usr/bin/env bash

set -uexo pipefail

dnf -y install default-flatpaks

rpm-ostree override remove \
    firefox \
    firefox-langpacks

rpm-ostree override remove \
    akonadi-server \
    akonadi-server-mysql \
    ark \
    ark-libs \
    bluez-cups \
    braille-printer-app \
    c2esp \
    colord-kde \
    cups \
    cups-browsed \
    cups-filters \
    cups-filters-driverless \
    default-fonts-core-mono \
    default-fonts-core-serif \
    default-fonts-other-mono \
    default-fonts-other-serif \
    dymo-cups-drivers \
    filelight \
    ghostscript \
    ghostscript-tools-fontutils \
    ghostscript-tools-printing \
    google-droid-sans-fonts \
    google-noto-sans-mono-vf-fonts \
    google-noto-serif-fonts \
    google-noto-serif-vf-fonts \
    gutenprint-cups \
    hplip \
    ImageMagick \
    ImageMagick-libs \
    kcharselect \
    kdebugsettings \
    kde-connect \
    kdeconnectd \
    kde-connect-libs \
    khelpcenter \
    kinfocenter \
    kwrite \
    langpacks-en \
    langpacks-fonts-en \
    libcupsfilters \
    libgs \
    libppd \
    phonon-backend-vlc-common \
    phonon-qt6-backend-vlc \
    plasma-desktop-doc \
    plasma-print-manager \
    plasma-print-manager-libs \
    plasma-systemmonitor \
    plasma-workspace-wallpapers \
    printer-driver-brlaser \
    ptouch-driver \
    splix \
    vlc-libs \
    vlc-plugin-ffmpeg \
    vlc-plugin-gstreamer \
    vlc-plugin-pipewire \
    vlc-plugin-pulseaudio \
    vlc-plugins-base \
    vlc-plugins-video-out
