ARG from
FROM $from

RUN dnf -y install \
    @kde-desktop \
    fedora-release-kinoite \
    plasma-discover-rpm-ostree \
    NetworkManager-wifi \
    --exclude 'kernel-*' \
    --exclude PackageKit-command-not-found \
    --exclude PackageKit \
    --exclude plasma-nm-l2tp \
    --exclude NetworkManager-l2tp \
    --exclude xl2tpd \
    --exclude glibc-all-langpacks \
    --exclude ark \
    --exclude filelight \
    --exclude kcharselect \
    --exclude kdebugsettings \
    --exclude kde-connect \
    --exclude khelpcenter \
    --exclude kinfocenter \
    --exclude kwrite \
    --exclude plasma-systemmonitor \
    --exclude akonadi-server \
    --exclude akonadi-server-mysql \
    --exclude colord-kde \
    --exclude cups-pk-helper \
    --exclude plasma-print-manager \
    --exclude plasma-workspace-wallpapers \
    --exclude plasma-desktop-doc \
    --exclude phonon-qt6-backend-vlc \
    --exclude vlc-libs \
    --exclude vlc-plugins-base \
    --exclude vlc-plugin-pulseaudio \
    --exclude vlc-plugin-gstreamer \
    --exclude phonon-backend-vlc-common \
    --exclude google-droid-sans-fonts \
    --exclude google-noto-serif-fonts \
    --exclude google-noto-sans-mono-vf-fonts \
    --exclude google-noto-serif-vf-fonts \
    --exclude qt5-qtwebkit \
    --exclude kwebkitpart

RUN systemctl enable sddm.service

# cleanup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
