ARG from
FROM $from

RUN dnf -y install \
        @kde-desktop \
        plasma-discover-rpm-ostree \
        fedora-release-kinoite \
        --exclude ark \
        --exclude filelight \
        --exclude kcharselect \
        --exclude kdebugsettings \
        --exclude khelpcenter \
        --exclude kinfocenter \
        --exclude kwrite \
        --exclude plasma-systemmonitor && \
    systemctl enable sddm.service && \
    dnf clean all
