#!/usr/bin/env bash

set -uexo pipefail

# Files

cp -arfT files/etc /etc

if [ "$xiaomi_nabu_samsung_ufs" = "true" ]; then
    cp -arfT files/samsung/etc /etc
fi

# Packages

dnf -y install \
    xiaomi-nabu-configs \
    alsa-ucm-conf-sm8150 \
    ath10k-shutdown \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr

# Services

systemctl enable \
    tqftpserv.service \
    rmtfs.service \
    qbootctl.service

# droid-juicer

cp -arfT files/droid-juicer/etc /etc
cp -arfT files/droid-juicer/usr /usr

dnf -y install \
    qcom-firmware \
    droid-juicer \
    make-dynpart-mappings

rm -rf /etc/droid-juicer || true

systemctl enable \
    droid-juicer.service \
    ostree-state-overlay@usr-lib-firmware-updates.service

# Kernel

mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
rm -rf /usr/lib/modules/*
dnf -y install kernel
rm -r /boot/dtb
