ARG from
FROM $from

RUN dnf -y install \
        @kde-mobile-environment \
        plasma-discover-rpm-ostree \
        NetworkManager-wifi \
        --exclude ark \
        --exclude filelight \
        --exclude kcharselect \
        --exclude kdebugsettings \
        --exclude khelpcenter \
        --exclude kinfocenter \
        --exclude kwrite \
        --exclude plasma-systemmonitor \
        --exclude angelfish \
        --exclude arianna \
        --exclude elisa-player \
        --exclude haruna \
        --exclude kalk \
        --exclude kasts \
        --exclude kclock \
        --exclude keysmith \
        --exclude koko \
        --exclude krecorder \
        --exclude kweather \
        --exclude marknote \
        --exclude neochat \
        --exclude okular-mobile \
        --exclude qrca \
        --exclude spacebar \
        --exclude tokodon && \
    systemctl enable sddm.service && \
    dnf clean all
