ARG from
FROM $from

ARG target_tag

RUN dnf -y install \
    @kde-mobile-environment \
    plasma-discover-rpm-ostree \
    NetworkManager-wifi \
    --exclude PackageKit \
    --exclude ark \
    --exclude filelight \
    --exclude kcharselect \
    --exclude kdebugsettings \
    --exclude khelpcenter \
    --exclude kinfocenter \
    --exclude kwrite \
    --exclude plasma-systemmonitor \
    --exclude angelfish \
    --exclude arianna \
    --exclude elisa-player \
    --exclude haruna \
    --exclude kalk \
    --exclude kasts \
    --exclude kclock \
    --exclude keysmith \
    --exclude koko \
    --exclude krecorder \
    --exclude kweather \
    --exclude marknote \
    --exclude neochat \
    --exclude okular-mobile \
    --exclude qrca \
    --exclude spacebar \
    --exclude tokodon \
    --exclude phonon-qt6-backend-vlc \
    --exclude vlc-libs \
    --exclude vlc-plugins-base \
    --exclude vlc-plugin-pulseaudio \
    --exclude vlc-plugin-gstreamer \
    --exclude phonon-backend-vlc-common \
    --exclude google-droid-sans-fonts \
    --exclude google-noto-serif-fonts \
    --exclude google-noto-sans-mono-vf-fonts \
    --exclude google-noto-serif-vf-fonts

RUN systemctl enable sddm.service

# os-release file
RUN sed -i "s/^PRETTY_NAME=.*/PRETTY_NAME=\"Fedora Linux $target_tag (plasma-mobile)\"/" /usr/lib/os-release

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
