ARG from
FROM $from

RUN dnf -y install \
    # TODO: remove coreutils-single from mipad6 kernel deps
    # TODO: then remove --allowerasing
    --allowerasing \
    @kde-mobile-environment \
    plasma-discover-rpm-ostree \
    NetworkManager-wifi \
    --exclude PackageKit \
    --exclude ark \
    --exclude filelight \
    --exclude kcharselect \
    --exclude kdebugsettings \
    --exclude khelpcenter \
    --exclude kinfocenter \
    --exclude kwrite \
    --exclude plasma-systemmonitor \
    --exclude angelfish \
    --exclude arianna \
    --exclude elisa-player \
    --exclude haruna \
    --exclude kalk \
    --exclude kasts \
    --exclude kclock \
    --exclude keysmith \
    --exclude koko \
    --exclude krecorder \
    --exclude kweather \
    --exclude marknote \
    --exclude neochat \
    --exclude okular-mobile \
    --exclude qrca \
    --exclude spacebar \
    --exclude tokodon \
    --exclude phonon-qt6-backend-vlc \
    --exclude vlc-libs \
    --exclude vlc-plugins-base \
    --exclude vlc-plugin-pulseaudio \
    --exclude vlc-plugin-gstreamer \
    --exclude phonon-backend-vlc-common \
    --exclude google-droid-sans-fonts \
    --exclude google-noto-serif-fonts \
    --exclude google-noto-sans-mono-vf-fonts \
    --exclude google-noto-serif-vf-fonts

RUN systemctl enable sddm.service

# cleanup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
