ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

# kernel
RUN mkdir /boot/dtb && \
    dnf -y remove kernel && \
    dnf -y install kernel kernel-modules-extra && \
    rm -rf /boot/dtb

# firmware
RUN dnf -y install \
    bcm283x-firmware \
    qcom-firmware

# qualcomm tools and libs
RUN dnf -y install \
    libssc \
    hexagonrpc \
    pil-squasher \
    qbootctl \
    bootmac

# audio
RUN dnf -y install \
    alsa-utils \
    pipewire \
    pipewire-alsa \
    pipewire-pulseaudio \
    alsa-ucm-mobility-sdm845

# usb network
RUN dnf -y install \
    dnsmasq

# other
RUN dnf -y install \
    mobility-tweaks \
    buffyboard

RUN systemctl enable \
    qbootctl.service \
    bootmac-bluetooth.service \
    hexagonrpcd-sdsp.service \
    msm-modem-uim-selection.service
RUN systemctl disable bootc-fetch-apply-updates.timer

# firmware
COPY fwload/usr/ /usr/
COPY fwload/firmware-oneplus-sdm845/usr /usr/
COPY fwload/firmware-oneplus-sdm845/lib /usr/lib/
RUN mkdir -p /usr/lib/firmware/updates && \
    mv /usr/lib/firmware/postmarketos/* /usr/lib/firmware/updates && \
    rmdir /usr/lib/firmware/postmarketos

COPY usbnet/etc/ /etc/
COPY usbnet/usr/ /usr/

# cleanup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint
