ARG base_tag

FROM quay.io/fedora/fedora-bootc:$base_tag

COPY etc/ /etc/
COPY usr/ /usr/

# workaround (see https://github.com/ublue-os/bluefin-lts/issues/3)
RUN mkdir -p /var/roothome

RUN dnf -y install 'dnf5-command(copr)' && \
    dnf -y copr enable gmanka/sdm845 && \
    dnf -y copr enable onesaladleaf/mobility-common && \
    dnf -y install kernel-0:6.15.0-0.rc2.15.sdm845.* kernel-modules-extra && \
    dnf -y install \
        @core \
        @hardware-support \
        @standard \
        @base-graphical \
        --exclude dracut-config-rescue && \
    dnf -y install \
        bcm283x-firmware \
        qcom-firmware \
        grub2-efi-aa64 grub2-efi-aa64-modules grubby \
        systemd-oomd-defaults systemd-resolved \
        glibc-langpack-en \
        btrfs-progs udisks2-btrfs \
        bootmac hexagonrpc libssc pd-mapper qrtr rmtfs alsa-ucm-mobility-sdm845 qbootctl \
        fedora-release-ostree-desktop \
        fedora-release-mobility \
        mobility-tweaks \
        iio-sensor-proxy \
        vim && \
    systemctl enable bootmac-bluetooth.service && \
    systemctl enable hexagonrpcd-sdsp.service && \
    systemctl enable pd-mapper.service && \
    systemctl enable rmtfs.service && \
    systemctl enable qbootctl.service && \
    dnf clean all

RUN if [ "$base_tag" = "rawhide" ]; then \
    dnf -y install tqftpserv && \
    systemctl enable tqftpserv.service && \
    dnf clean all; \
fi

COPY firmware-oneplus-sdm845/usr /usr/
COPY firmware-oneplus-sdm845/lib /usr/lib/
RUN mv /usr/lib/firmware/qcom/sdm845/oneplus6/ipa_fws.mbn{,.disabled} && \
    mv /usr/lib/firmware/postmarketos/* /usr/lib/firmware/updates && \
    rmdir /usr/lib/firmware/postmarketos
