ARG from
FROM $from

ARG target_tag

COPY etc/ /etc/

RUN dnf -y install \
    xiaomi-nabu-configs \
    xiaomi-nabu-firmware \
    alsa-ucm-conf-sm8150 \
    ath10k-shutdown \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    rm -rf /usr/lib/modules/* && \
    dnf -y install kernel && \
    rm -r /boot/dtb

# services
RUN systemctl enable \
    tqftpserv.service \
    rmtfs.service \
    qbootctl.service

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
