ARG from
FROM $from

ARG target_tag

COPY etc/ /etc/
COPY var/ /var/

RUN dnf -y install \
    xiaomi-pipa-firmware \
    qbootctl \
    pipa-dracut \
    pipa-sound-conf \
    bootmac

# kernel
RUN mkdir -p /boot/dtb && \
    dnf -y remove \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core && \
    rm -rf /usr/lib/modules/* && \
    dnf -y install \
        kernel \
        kernel-headers && \
    rm -r /boot/dtb

# services
RUN systemctl enable \
    qbootctl.service \
    bootmac-bluetooth

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
