#!/usr/bin/env bash

set -uexo pipefail

dnf -y install default-flatpaks

rpm-ostree override remove \
    firefox \
    firefox-langpacks

rpm-ostree override remove \
    gnome-classic-session \
    gnome-system-monitor \
    gnome-user-docs \
    gnome-tour \
    malcontent-control \
    yelp
