ARG base_name
ARG base_tag

FROM quay.io/pocketblue/$base_name:$base_tag

RUN dnf -y install \
        @phosh-desktop \
        gnome-shell \
        ptyxis \
        --exclude \
        gnome-console,gnome-photos,phoc,phosh,squeekboard && \
    systemctl enable gdm.service && \
    dnf clean all
