# FP5 firmware
install_items+=" /lib/firmware/qcom/qcm6490/fairphone5 "

# GPU SQE (Shader/Sequencer Engine) firmware for Adreno 660 (from qcom-firmware)
install_items+=" /lib/firmware/qcom/a660_sqe.fw.xz "
install_items+=" /lib/firmware/qcom/a660_gmu.bin.xz "
