#!/usr/bin/env bash

set -uexo pipefail

cp -arfT files/etc /etc
cp -arfT files/usr /usr

# workaround (see https://github.com/ublue-os/bluefin-lts/issues/3)
mkdir -p /var/roothome

# setup development tools
dnf -y install git just buildah
systemctl enable sshd.service

# only keep the EN langpack to decrease image size
dnf -y swap glibc-all-langpacks glibc-langpack-en

dnf -y remove dracut-config-rescue
