#!/usr/bin/env bash

set -uexo pipefail

sed -i "s/^PRETTY_NAME=.*/PRETTY_NAME=\"Fedora Linux ${target_tag} (${desktop})\"/" /usr/lib/os-release

dnf5 clean all

find /var/* -maxdepth 0 -type d \! -name cache -exec rm -fr {} \;

mkdir -p /var/tmp
chmod -R 1777 /var/tmp
