#!/usr/bin/env bash

set -uexo pipefail

cp -arfT etc /etc

dnf -y remove gnome-shell mutter gnome-settings-daemon
dnf -y install gnome-shell mutter gnome-settings-daemon

dnf -y install \
    default-flatpaks \
    gnome-shell-extension-nekotorch

rpm-ostree override remove \
    firefox \
    firefox-langpacks

rpm-ostree override remove \
    gnome-system-monitor \
    gnome-user-docs \
    gnome-tour \
    malcontent-control \
    yelp
