ARG base_name
ARG base_tag

FROM quay.io/pocketblue/$base_name:$base_tag

RUN dnf -y install 'dnf5-command(copr)' && \
    dnf -y copr enable @mobility/gnome-mobile && \
    # @gnome-desktop comes with a lot of components unnecessary for mobile devices. \
    # For now, install @phosh-desktop and replace phosh with gnome-mobile \
    dnf -y install \
        @phosh-desktop \
        gnome-shell-0:*^mobile* \
        ptyxis \
        --exclude \
        gnome-console,gnome-photos,phoc,phosh,squeekboard && \
    systemctl enable gdm.service && \
    dnf clean all
