#!/usr/bin/env bash

set -uexo pipefail

cp -arfT files/usr /usr
cp -arfT files/etc /etc

# packages
dnf -y install \
    gnome-text-editor \
    alsa-utils \
    alsa-ucm-utils \
    alsa-topology-utils \
    alsabat \
    bluez \
    libcamera \
    libcamera-tools \
    libcamera-ipa \
    libcamera-gstreamer \
    libcamera-qcam \
    libssc \
    libiio-utils \
    qbootctl \
    qrtr \
    rmtfs \
    tqftpserv \
    usb_modeswitch \
    v4l-utils \
    media-ctl \
    snapshot

dnf -y install --repo='copr:copr.fedorainfracloud.org:lorbus:misc' \
    hexagonrpc

# Re-Install iio-sensor-proxy with Qualcomm SSC support (from COPR)
# https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/merge_requests/381
dnf -y swap --repo='copr:copr.fedorainfracloud.org:lorbus:misc' \
    iio-sensor-proxy iio-sensor-proxy

# kernel (from lorbus/misc copr)
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-modules-extra
dnf -y install --refresh --repo='copr:copr.fedorainfracloud.org:lorbus:misc' \
    kernel

# Set executable permissions on helper scripts
chmod +x /usr/libexec/fairphone-fp5-debug
chmod +x /usr/libexec/set-bt-mac

# Install SELinux policy module for QRTR socket access (CIL format)
# Fedora's iiosensorproxy_t domain lacks permission for qipcrtr_socket
semodule -X 400 -i /usr/share/selinux/packages/iio-sensor-proxy-qrtr.cil

systemctl enable \
    hexagonrpcd-adsp-sensorspd.service \
    hexagonrpcd-adsp-rootpd.service \
    bluetooth.service \
    tqftpserv.service \
    qbootctl.service \
    rmtfs.service

# Mask services that don't apply to mobile ARM devices:
# - bootloader-update: uses bootupd for EFI systems; FP5 uses Android A/B boot
systemctl mask \
    bootloader-update.service

KERNEL_SUFFIX=""
QUALIFIED_KERNEL="$(rpm -qa | grep -P 'kernel-(|'"$KERNEL_SUFFIX"'-)(\d+\.\d+\.\d+)' | sed -E 's/kernel-(|'"$KERNEL_SUFFIX"'-)//')"
export DRACUT_NO_XATTR=1
/usr/bin/dracut --no-hostonly --kver "$QUALIFIED_KERNEL" --reproducible -v --add ostree -f "/lib/modules/$QUALIFIED_KERNEL/initramfs.img"
chmod 0600 "/lib/modules/$QUALIFIED_KERNEL/initramfs.img"
