#!/usr/bin/env bash

set -uexo pipefail

cp -arfT files/etc /etc
cp -arfT files/usr /usr

dnf -y install uwe5622-firmware

mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core
rm -rf /usr/lib/modules/*
dnf -y install kernel
rm -r /boot/dtb

echo 123456 | passwd root --stdin
