on:
  workflow_call:
    inputs:
      # container's base image
      fedora_branch:
        required: true
        type: string

      # image to build
      registry:
        required: true
        type: string
      device:
        required: true
        type: string
      desktop:
        required: true
        type: string
      tag:
        required: true
        type: string

      # misc parameters
      latest:
        required: false
        type: string
        default: ''
      expires:
        required: false
        type: string
        default: ''

jobs:
  build:
    name: ${{ inputs.device }}-${{ inputs.desktop }}
    runs-on: ubuntu-26.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Get device config
        id: conf
        shell: bash
        run: |
          cat 'devices/${{ inputs.device }}/build-aux/device.conf' >> $GITHUB_OUTPUT

      - name: Prepare environment
        env:
          INPUT_REGISTRY: ${{ inputs.registry }}
          REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME || github.repository_owner }}
        run: |
          echo "REGISTRY_USERNAME=${REGISTRY_USERNAME,,}" >> ${GITHUB_ENV}

          if [ -z "${{ steps.conf.outputs.device_variant }}" ]; then
            echo "PB_TAG=${{ inputs.tag }}" >> $GITHUB_ENV
            echo "TARGET_IMAGE_NAME=${{ inputs.device }}-${{ inputs.desktop }}" >> $GITHUB_ENV
          else
            pb_tag="${{ inputs.tag }}-${{ steps.conf.outputs.device_variant }}"
            target_image_name="${{ steps.conf.outputs.device_base }}-${{ inputs.desktop }}"

            echo "PB_TAG=$pb_tag" >> $GITHUB_ENV
            echo "PB_FULL_IMAGE=${INPUT_REGISTRY,,}/${target_image_name}:${pb_tag}" >> $GITHUB_ENV
            echo "TARGET_IMAGE_NAME=$target_image_name" >> $GITHUB_ENV
          fi

          cat >> ${GITHUB_ENV} << EOF
          PB_BRANCH=${{ inputs.fedora_branch }}
          PB_DEVICE=${{ inputs.device }}
          PB_DESKTOP=${{ inputs.desktop }}
          PB_REGISTRY=${INPUT_REGISTRY,,}
          PB_EXPIRES_AFTER=${{ inputs.expires && '1w' || '' }}
          PB_RECHUNK_SUFFIX=-build
          EOF

      - uses: extractions/setup-just@v4
        with:
          just-version: '1.46.0'

      - name: Pull
        id: pull
        run: |
          just pull

      - name: Build
        id: build
        run: just build

      - name: Rechunk
        id: rechunk
        run: |
          just rechunk

      - name: Push
        id: push
        uses: pocketblue/actions/container-push@main
        env:
          latest: ${{ inputs.latest }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
          registry: ${{ env.PB_REGISTRY }}
          signing_key: ${{ secrets.SIGNING_KEY }}
          name: ${{ env.TARGET_IMAGE_NAME }}
          tag: ${{ env.PB_TAG }}
